# install.packages("devtools")
# library(devtools)
# install_github("Diviyan-Kalainathan/RCIT")
# install.packages("RBGL")
# BiocManager::install("graph", version = "3.1a8")
BiocManager::install("SID")
library(kpcalg)
library(pcalg)
library(SID)
RCIT(rnorm(1000),rnorm(1000),rnorm(1000))
RCoT(rnorm(1000),rnorm(1000),rnorm(1000))
